---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: klum-operator
  labels:
    app.kubernetes.io/name: klum-operator
    app.kubernetes.io/component: operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

subjects:
  - kind: ServiceAccount
    name: klum-operator

...
